/**
 * RuneScape: Dragonwilds - DedicatedServer.ini. Unreal-style INI; every setting
 * lives under [/Script/Dominion.DedicatedServerSettings].
 *
 * Case must not matter here. Jagex's guide spells the section in PascalCase
 * while the server itself writes `[/script/dominion.dedicatedserversettings]`,
 * so the registry parses this file case-insensitively (as it does ARK's). A
 * case-sensitive match would find none of the keys, render every field empty,
 * and append a second section on save - the exact corruption that option exists
 * to prevent.
 *
 * The file is deliberately small, and what it lacks matters as much as what it
 * holds: no player limit (the server is capped at 6 and takes no key for it),
 * no difficulty (`DifficultyType` exists in the build but is not read from this
 * file), and no ports (7777/7778 UDP come from the command line).
 *
 * `ServerGuid` is surfaced under Server / Identity so it is findable, but it is
 * generated by the server and Jagex says not to edit it - hence the label. It is
 * a `t` field like the rest because the form has no read-only text control; the
 * warning is the guard.
 *
 * `bCanSaveAllSections` is Unreal's config-save bookkeeping rather than a game
 * setting, and it lives in `[SectionsToSave]`, but it is shown under Server /
 * Identity because it governs whether the server rewrites this file at all -
 * which is the thing most likely to eat an edit made here.
 *
 * `Public` is the one field here that is not in Jagex's documented five. It
 * appears in server-written files as `Public=1` and controls the Epic Online
 * Services listing, so it is offered as a toggle; the format counts `1` as true
 * (see the codec note in registry.ts) so an existing `Public=1` reads as on
 * instead of silently showing off.
 */
import type { Schema } from '../../formats/types';
import { section } from '../fields';

const s = section('/Script/Dominion.DedicatedServerSettings');
// bCanSaveAllSections lives in its own [SectionsToSave] section, not with the
// game settings. A group can mix sections freely - the address carries the
// section with it - so it can be shown next to the identity fields while still
// reading and writing the right line.
const saves = section('SectionsToSave');

export const dragonwildsSchema: Schema = [
    {
        id: 'identity',
        title: 'Server / Identity',
        icon: 'fa-solid fa-id-card',
        fields: [
            s.t('ServerName', 'Server name (shown in the browser)'),
            s.t('DefaultWorldName', 'Default world name (names the world only when it is first created)'),
            s.b('Public', 'Announce on Epic Online Services (public server browser)'),
            s.t('ServerGuid', 'Server GUID (generated by the server - do not edit)'),
            saves.b('bCanSaveAllSections', 'Let the server write all config sections back to this file'),
        ],
    },
    {
        id: 'access',
        title: 'Ownership & Passwords',
        icon: 'fa-solid fa-key',
        fields: [
            s.t('OwnerId', 'Owner Player ID (required - the server will not start without it)'),
            s.t('AdminPassword', 'Admin password (unlocks the Server Management tab)'),
            s.t('WorldPassword', 'World password (empty = anyone can join)'),
        ],
    },
];
