/** Palworld PalWorldSettings.ini - full schema across 11 groups. */
import type { Schema } from '../../formats/types';
import { n, b, t, sel } from '../fields';

export const palworldSchema: Schema = [
    {
        id: 'server',
        title: 'Server / Identity',
        icon: 'id-card',
        fields: [
            t('ServerName', 'Server name'),
            t('ServerDescription', 'Description'),
            t('ServerPassword', 'Server password'),
            t('AdminPassword', 'Admin password'),
            t('Region', 'Region'),
            b('bUseAuth', 'Require authentication'),
            t('BanListURL', 'Ban list URL'),
            sel('AllowConnectPlatform', 'Allowed platform', ['Steam', 'Xbox']),
        ],
    },
    {
        id: 'multiplayer',
        title: 'Players & Multiplayer',
        icon: 'users',
        fields: [
            n('ServerPlayerMaxNum', 'Max players'),
            n('CoopPlayerMaxNum', 'Co-op players (guild)'),
            b('bIsMultiplay', 'Multiplay'),
            b('bIsPvP', 'PvP'),
            b('bEnablePlayerToPlayerDamage', 'Player-to-player damage'),
            b('bEnableFriendlyFire', 'Friendly fire'),
            b('bHardcore', 'Hardcore'),
            b('bPalLost', 'Lose Pals on death (hardcore)'),
            b('bEnableNonLoginPenalty', 'Non-login penalty'),
            b('bEnableFastTravel', 'Fast travel'),
            b('bIsStartLocationSelectByMap', 'Pick start location on map'),
            b('bExistPlayerAfterLogout', 'Body persists after logout'),
            b('bEnableInvaderEnemy', 'Invader enemies'),
            b('bActiveUNKO', 'Active UNKO'),
            b('bEnableAimAssistPad', 'Aim assist (gamepad)'),
            b('bEnableAimAssistKeyboard', 'Aim assist (keyboard)'),
        ],
    },
    {
        id: 'world',
        title: 'World & Difficulty',
        icon: 'earth-americas',
        fields: [
            sel('Difficulty', 'Difficulty', ['None', 'Casual', 'Normal', 'Hard']),
            sel('RandomizerType', 'Randomizer type', ['None', 'Region', 'All']),
            t('RandomizerSeed', 'Randomizer seed'),
            sel('DeathPenalty', 'Death penalty', ['none', 'Item', 'ItemAndEquipment', 'All']),
            n('DayTimeSpeedRate', 'Day-time speed rate'),
            n('NightTimeSpeedRate', 'Night-time speed rate'),
            b('bIsUseBackupSaveData', 'Backup save data'),
            n('AutoSaveSpan', 'Auto-save interval (s)'),
            n('SupplyDropSpan', 'Supply drop interval (min)'),
        ],
    },
    {
        id: 'rates_progress',
        title: 'Rates - Progression & Gathering',
        icon: 'gauge-high',
        fields: [
            n('ExpRate', 'EXP rate'),
            n('PalCaptureRate', 'Pal capture rate'),
            n('PalSpawnNumRate', 'Pal spawn rate'),
            n('WorkSpeedRate', 'Work speed rate'),
            n('CollectionDropRate', 'Gather drop rate'),
            n('CollectionObjectHpRate', 'Gatherable HP rate'),
            n('CollectionObjectRespawnSpeedRate', 'Gatherable respawn rate'),
            n('EnemyDropItemRate', 'Enemy drop rate'),
            n('ItemWeightRate', 'Item weight rate'),
        ],
    },
    {
        id: 'rates_combat',
        title: 'Rates - Combat & Structures',
        icon: 'gavel',
        fields: [
            n('PalDamageRateAttack', 'Pal damage - attack'),
            n('PalDamageRateDefense', 'Pal damage - defense'),
            n('PlayerDamageRateAttack', 'Player damage - attack'),
            n('PlayerDamageRateDefense', 'Player damage - defense'),
            n('BuildObjectHpRate', 'Structure HP rate'),
            n('BuildObjectDamageRate', 'Structure damage rate'),
            n('BuildObjectDeteriorationDamageRate', 'Structure decay rate'),
        ],
    },
    {
        id: 'rates_survival',
        title: 'Rates - Survival',
        icon: 'heart-pulse',
        fields: [
            n('PlayerStomachDecreaceRate', 'Player hunger drain'),
            n('PlayerStaminaDecreaceRate', 'Player stamina drain'),
            n('PlayerAutoHPRegeneRate', 'Player HP regen'),
            n('PlayerAutoHpRegeneRateInSleep', 'Player HP regen (sleep)'),
            n('PalStomachDecreaceRate', 'Pal hunger drain'),
            n('PalStaminaDecreaceRate', 'Pal stamina drain'),
            n('PalAutoHPRegeneRate', 'Pal HP regen'),
            n('PalAutoHpRegeneRateInSleep', 'Pal HP regen (sleep)'),
        ],
    },
    {
        id: 'pals',
        title: 'Pals',
        icon: 'paw',
        fields: [n('PalEggDefaultHatchingTime', 'Egg hatch time (h)'), b('EnablePredatorBossPal', 'Predator boss Pals')],
    },
    {
        id: 'items',
        title: 'Items & Drops',
        icon: 'box-open',
        fields: [
            n('DropItemMaxNum', 'Max dropped items'),
            n('DropItemMaxNum_UNKO', 'Max dropped items (UNKO)'),
            n('DropItemAliveMaxHours', 'Dropped item lifetime (h)'),
        ],
    },
    {
        id: 'base',
        title: 'Bases & Guilds',
        icon: 'warehouse',
        fields: [
            n('BaseCampMaxNum', 'Max base camps'),
            n('BaseCampWorkerMaxNum', 'Max base workers'),
            n('BaseCampMaxNumInGuild', 'Max bases per guild'),
            n('GuildPlayerMaxNum', 'Max guild players'),
            n('MaxBuildingLimitNum', 'Building limit (0 = unlimited)'),
            b('bAutoResetGuildNoOnlinePlayers', 'Auto-reset empty guilds'),
            n('AutoResetGuildTimeNoOnlinePlayers', 'Guild reset time (h)'),
            b('bCanPickupOtherGuildDeathPenaltyDrop', 'Pick up drops from other guilds'),
            b('bEnableDefenseOtherGuildPlayer', 'Defend vs other guilds'),
            b('bInvisibleOtherGuildBaseCampAreaFX', 'Hide other guild base FX'),
            b('bBuildAreaLimit', 'Build area limit'),
        ],
    },
    {
        id: 'misc',
        title: 'Chat & Misc',
        icon: 'comment',
        fields: [
            n('ChatPostLimitPerMinute', 'Chat posts / minute'),
            b('bShowPlayerList', 'Show player list'),
            sel('LogFormatType', 'Log format', ['Text', 'Json']),
            n('ServerReplicatePawnCullDistance', 'Pawn cull distance'),
        ],
    },
    {
        id: 'network',
        title: 'Networking / Relay',
        icon: 'network-wired',
        fields: [
            t('PublicIP', 'Public IP (empty behind a relay)'),
            n('PublicPort', 'Public port'),
            b('RCONEnabled', 'RCON enabled'),
            n('RCONPort', 'RCON port'),
            b('RESTAPIEnabled', 'REST API enabled'),
            n('RESTAPIPort', 'REST API port'),
        ],
    },
];
